#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "gokapi"
name = "Gokapi"
description.en = "Lightweight server to share files"
description.fr = "Serveur léger pour partager des fichiers"

version = "2.2.4~ynh2"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0"
admindoc = "https://gokapi.readthedocs.io/"
code = "https://github.com/Forceu/Gokapi"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]

    [resources.sources.main]
    amd64.url = "https://github.com/Forceu/Gokapi/releases/download/v2.2.4/gokapi-2.2.4_linux-amd64.zip"
    amd64.sha256 = "51dbf724c94f8afa0b40fb1ef63a1fe418e7996e7b9536e1f0a5da695b8e18ef"
    i386.url = "https://github.com/Forceu/Gokapi/releases/download/v2.2.4/gokapi-2.2.4_linux-386.zip"
    i386.sha256 = "27c03e3aa30d6c146c6675c0b23da7c63571cb08468840790c9a6e0f0ddc0969"
    armhf.url = "https://github.com/Forceu/Gokapi/releases/download/v2.2.4/gokapi-2.2.4_linux-arm.zip"
    armhf.sha256 = "274428207bc4c7946b03f1857d25f5ff40365f82325cf07e41bd5058dce05b72"
    arm64.url = "https://github.com/Forceu/Gokapi/releases/download/v2.2.4/gokapi-2.2.4_linux-arm64.zip"
    arm64.sha256 = "9f82cfb96fc48ac9bdfb94584dc6ba4648de1ac4fcd1276d2dd5a7e0f80398f7"

    in_subdir = false

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^gokapi-\\d+(\\.\\d+)+_linux-amd64\\.zip"
    autoupdate.asset.i386 = "^gokapi-\\d+(\\.\\d+)+_linux-386\\.zip"
    autoupdate.asset.armhf = "^gokapi-\\d+(\\.\\d+)+_linux-arm\\.zip"
    autoupdate.asset.arm64 = "^gokapi-\\d+(\\.\\d+)+_linux-arm64\\.zip"

    [resources.sources.intermediate]
    amd64.url = "https://github.com/Forceu/Gokapi/releases/download/v2.0.0/gokapi-linux_amd64.zip"
    amd64.sha256 = "e9a87f606485cede6bdabf49de555e9c21469eccd6537e1d2feea042b7874b66"
    i386.url = "https://github.com/Forceu/Gokapi/releases/download/v2.0.0/gokapi-linux_386.zip"
    i386.sha256 = "836964e148b1843d6ef2b559dcce82bf140ffbadf5f6bec31e697d002f41ec5c"
    armhf.url = "https://github.com/Forceu/Gokapi/releases/download/v2.0.0/gokapi-linux_arm.zip"
    armhf.sha256 = "b445a648a17ff35a4c8305be10ce3ae3d3b27e49efd11ecd6dbbd824512370aa"
    arm64.url = "https://github.com/Forceu/Gokapi/releases/download/v2.0.0/gokapi-linux_arm64.zip"
    arm64.sha256 = "d986859a0bfdca7699d0a4ff20e01508c5fa6029724b44ce85df8a4157f11ae3"

    in_subdir = false
    prefetch = false

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    

    [resources.permissions]
    main.url = "/"

    [resources.ports]
