#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "gokapi"
name = "Gokapi"
description.en = "Lightweight server to share files"
description.fr = "Serveur léger pour partager des fichiers"

version = "1.9.6~ynh2"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0"
admindoc = "https://gokapi.readthedocs.io/"
code = "https://github.com/Forceu/Gokapi"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]

    [resources.sources.main]
    amd64.url = "https://github.com/Forceu/Gokapi/releases/download/v1.9.6/gokapi-linux_amd64.zip"
    amd64.sha256 = "f7a679d55a766633a08fe970d26c79224c5fe6f9f8f903ff3f7d369b60d8e03f"
    i386.url = "https://github.com/Forceu/Gokapi/releases/download/v1.9.6/gokapi-linux_amd64.zip"
    i386.sha256 = "f7a679d55a766633a08fe970d26c79224c5fe6f9f8f903ff3f7d369b60d8e03f"
    armhf.url = "https://github.com/Forceu/Gokapi/releases/download/v1.9.6/gokapi-linux_amd64.zip"
    armhf.sha256 = "f7a679d55a766633a08fe970d26c79224c5fe6f9f8f903ff3f7d369b60d8e03f"
    arm64.url = "https://github.com/Forceu/Gokapi/releases/download/v1.9.6/gokapi-linux_amd64.zip"
    arm64.sha256 = "f7a679d55a766633a08fe970d26c79224c5fe6f9f8f903ff3f7d369b60d8e03f"

    in_subdir = false

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "gokapi-linux_amd64\\.zip"
    autoupdate.asset.i386 = "gokapi-linux_386\\.zip"
    autoupdate.asset.armhf = "gokapi-linux_arm\\.zip"
    autoupdate.asset.arm64 = "gokapi-linux_arm64\\.zip"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
